# Change these first
owner: tonytins # Your GitHub username
repo: status # Your Github repository name

# Add your sites here
sites:
  - name: Peertube Instance
    url: https://video.tonybark.com

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.tonybark.com
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/tonytins/status/master/icon.svg
  name: Tony Bark Network Status
  introTitle: Tony Bark Network Status
  introMessage: Based on [Uptime](https://github.com/upptime/upptime), this status page keeps track of varies services I have running.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
